### PR TITLE
Prevent using -1 as index

### PR DESCRIPTION
**Pull request by holtkamp**
After encountering an edge case in https://github.com/abacaphiliac/doctrine-psr-sql-logger/pull/9

### CODE REVIEW

**Comment by abacaphiliac** [comment]
interesting. i think another test where the fallback value is selected would be useful. thoughts?

**Comment by holtkamp** [comment]
Note that I changed the test so that it uses the fallback...

Maybe it is not explicit enough, but my brain is a bit numb on this area now 😉 

Will give it a shot though, but feel free to jump in

**Comment by abacaphiliac** [comment]
i see. i think i need to tweak the coverage config and drop some tests in for branch coverage of new `else` conditions. i'll put it up and tag you, if you don't mind ; )

**Comment by holtkamp** [comment]
@abacaphiliac when cleaning up my `composer.json` I noticed I am still using `"abacaphiliac/doctrine-psr-sql-logger": "dev-master"` since the changes as discussed in this PR have been merged into master, but not tagged as a new (minor / patch) release. 

Were you planning on tagging a new release?

**Comment by abacaphiliac** [comment]
@holtkamp [1.1.0](https://github.com/abacaphiliac/doctrine-psr-sql-logger/releases/tag/1.1.0) has been tagged

**Pull request merged**
