### PR TITLE
Initial approach to allow query-duration based log-level configuration

### PR DESCRIPTION
**Pull request by holtkamp**
As suggested in https://github.com/abacaphiliac/doctrine-psr-sql-logger/issues/4

### CODE REVIEW

**Comment by abacaphiliac** [comment]
@holtkamp thanks for getting started on this! as discussed in #4, would you be willing to create a new logger class for this implementation? perhaps `PsrSqlLoggerConfigurableLogLevels`, as the test suggests, or i was thinking `PsrSlowQueryLogger`.

**Comment by holtkamp** [comment]
>would you be willing to create a new logger class for this implementation?

Ah, yeah, sure, done!

Question, how would you like to deal with these warnings?

>WARNING | Line exceeds 120 characters; contains 129 characters

For me the 120 characters is something from the previous decade 🤓 , most people have bigger screens now to work on...

And note that we can use [`PSR12`](https://www.php-fig.org/psr/psr-12/) as a replacement of `PSR2`, but it would be better to do that in a separate PR.

**Comment by abacaphiliac** [comment]
this is great!

i'd like to see a couple more assertions/tests, to cover each of the configured levels and boundaries between levels. it would also be interesting to see what happens if invalid levels are specified, if that is even possible. e.g. are invalid default levels and mappings ignored? are there fallback values? will it throw errors? if it throws errors, when? these types of misconfigurations feel like errors to me, and we should probably throw from the constructor. what do you think? i see that we throw the first time we try to log when an invalid level is supplied. i feel that should be moved to the constructor, in the spirit of failing fast.

at least one of the operations in the method responsible for determining the appropriate log level can be hoisted into the constructor, so that we don't have to get the configured duration values upon each log. maybe we can extract some more things?

the untyped level map makes me nervous, especially without clear documentation. is there a different structure we could use instead to strengthen this?

> For me the 120 characters is something from the previous decade 🤓 , most people have bigger screens now to work on...

you're right about that, but when i'm not working on my 15" laptop, i'm docked with split panes for viewing src and test simultaneously. i'd prefer to keep the limit as it is, for now.

> And note that we can use PSR12 as a replacement of PSR2, but it would be better to do that in a separate PR.

yes please!

**Comment by holtkamp** [comment]
>the untyped level map makes me nervous, especially without clear documentation. is there a different structure we could use instead to strengthen this?

You are right, isolating the `LogLevelConfiguration` in a separate class allows  the code to fail early. 

I am not really sure about the approach of how I "test" the scenario with an invalid `LogLevelConfiguration` though: the creator of PHPUnit [does not advise testing for TypeErrors](https://stackoverflow.com/a/34351099/187659). Using the PHP 7 types, we can be fairly sure the proper types are used.

**Comment by abacaphiliac** [comment]
@holtkamp this is really great. thanks for performing the refactor.

i suspect that this build will pass after a rebase now that `php:<7.1` has been dropped from master.

**Comment by abacaphiliac** [comment]
i was wondering what you thought about making the new classes `final`?

would you be able to add some usage docs to the readme describing this new functionality?

**Comment by abacaphiliac** [comment]
thank you for the contribution!

**Comment by holtkamp** [comment]
@abacaphiliac something I realize only now: based on the duration of the query, (only) the log-level of the log-entry written by`stopQuery()` function is influenced. But this log-entry:

- does not contain the actual SQL statement that is executed by the query
- does contain a `query_id`, but since `startQuery()` might have been filtered out due to a "low" log-level such as `DEBUG`, this identifier is probably useless

So in a production environment one would be able to tell: "some query is really slow", but not know which query exactly 😄 . What would you suggest? Also include the SQL statements as is done in `startQuery()`?

**Pull request merged**
