### PR TITLE
Allow PHP 8

### PR DESCRIPTION
**Pull request by holtkamp**

### CODE REVIEW

**Comment by abacaphiliac** [comment]
thanks, @holtkamp. would you mind please adding 8 to the travis config so that it will be included in the build matrix?

**Comment by holtkamp** [comment]
@abacaphiliac sorry for the delay, tried to combine the requested change with my previous, but apparently my GIT skills are still insufficient to "squash" commits... Should I start a new PR with a single commit? Or can you "squash and merge"?

**Comment by abacaphiliac** [comment]
Thanks for adding this. I'll take care of the rest, no problem.

**Comment by abacaphiliac** [comment]
hmm, something isn't quite right with the Travis CI integration. there are some issues with [this build](https://travis-ci.org/github/abacaphiliac/doctrine-psr-sql-logger/builds/752278894) but they aren't showing up in the checks. i'll have to dig in; might take advantage of this issue and switch from Travis CI to GitHub Actions.

**Comment by martinssipenko** [comment]
@abacaphiliac any updates with this? I'd like to use this in a project that uses PHP8. Perhaps you need help with this?

**Comment by abacaphiliac** [comment]
@holtkamp, @martinssipenko, thank you for your patience. i was really struggling with the switch from Travis CI to GitHub Actions and the right combinations of dependency ranges in the matrix builds to pave the way for php@8... and then time got away from me, so apologies for that.

i split the effort and got GitHub Actions working in #20, and now have #21 ready to go which did require additional changes.

@holtkamp, i rebased on top of your first commit from #18 so you'll still get credit. i'm proposing that we close #18 in favor of #21. what do you think?

**Comment by holtkamp** [comment]
@abacaphiliac you did some nice puzzling indeed! Compliments for the clean and structured way of working. Closing this PR in favor of https://github.com/abacaphiliac/doctrine-psr-sql-logger/pull/21 as suggested 👍

**Comment by abacaphiliac** [comment]
@holtkamp thanks for hanging in there with me on this. [1.2.0](https://github.com/abacaphiliac/doctrine-psr-sql-logger/tree/1.2.0) has been tagged.

**Pull request closed without merging**
